//                                   _           _    __ _ _        //
//                                  | |         | |  / _(_) |       //
//    __ _  ___ _ __   ___ _ __ __ _| |_ ___  __| | | |_ _| | ___   //
//   / _` |/ _ \ '_ \ / _ \ '__/ _` | __/ _ \/ _` | |  _| | |/ _ \  //
//  | (_| |  __/ | | |  __/ | | (_| | ||  __/ (_| | | | | | |  __/  //
//   \__, |\___|_| |_|\___|_|  \__,_|\__\___|\__,_| |_| |_|_|\___|  //
//    __/ |                                                         //
//   |___/                                                          //
//                                                                  //
// Generated by:  libraries/chain_id/identify_chain.cpp             //
//                                                                  //
// Warning: This is a generated file, any changes made here will be //
// overwritten by the build process.  If you need to change what    //
// is generated here, you should use the CMake variable             //
// GRAPHENE_EGENESIS_JSON to specify an embedded genesis state.     //
//                                                                  //

/*
 * Copyright (c) 2015, Cryptonomex, Inc.
 * All rights reserved.
 *
 * This source code is provided for evaluation in private test networks only, until September 8, 2015. After this date, this license expires and
 * the code may not be used, modified or distributed for any purpose. Redistribution and use in source and binary forms, with or without modification,
 * are permitted until September 8, 2015, provided that the following conditions are met:
 *
 * 1. The code and/or derivative works are used only for private test networks consisting of no more than 10 P2P nodes.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include <graphene/chain/protocol/types.hpp>
#include <graphene/egenesis/egenesis.hpp>

namespace graphene { namespace egenesis {

using namespace graphene::chain;

static const char genesis_json_array[246][40+1] =
{
"{\n  \"initial_timestamp\": \"2017-11-08T06:",
"45:30\",\n  \"max_core_supply\": \"1000000000",
"000000\",\n  \"initial_parameters\": {\n    \"",
"current_fees\": {\n      \"parameters\": [[\n",
"          0,{\n            \"fee\": 2000000",
",\n            \"price_per_kbyte\": 1000000",
"\n          }\n        ],[\n          1,{\n ",
"           \"fee\": 500000\n          }\n   ",
"     ],[\n          2,{\n            \"fee\"",
": 0\n          }\n        ],[\n          3,",
"{\n            \"fee\": 2000000\n          }",
"\n        ],[\n          4,{}\n        ],[\n",
"          5,{\n            \"basic_fee\": 5",
"00000,\n            \"premium_fee\": 200000",
"000,\n            \"price_per_kbyte\": 1000",
"00\n          }\n        ],[\n          6,{",
"\n            \"fee\": 2000000,\n           ",
" \"price_per_kbyte\": 100000\n          }\n ",
"       ],[\n          7,{\n            \"fe",
"e\": 300000\n          }\n        ],[\n     ",
"     8,{\n            \"membership_annual_",
"fee\": 200000000,\n            \"membership",
"_lifetime_fee\": 1000000000\n          }\n ",
"       ],[\n          9,{\n            \"fe",
"e\": 50000000\n          }\n        ],[\n   ",
"       10,{\n            \"symbol3\": \"5000",
"0000000\",\n            \"symbol4\": \"300000",
"00000\",\n            \"long_symbol\": 50000",
"0000,\n            \"price_per_kbyte\": 10\n",
"          }\n        ],[\n          11,{\n ",
"           \"fee\": 50000000,\n            ",
"\"price_per_kbyte\": 10\n          }\n      ",
"  ],[\n          12,{\n            \"fee\": ",
"50000000\n          }\n        ],[\n       ",
"   13,{\n            \"fee\": 50000000\n    ",
"      }\n        ],[\n          14,{\n     ",
"       \"fee\": 2000000,\n            \"pric",
"e_per_kbyte\": 100000\n          }\n       ",
" ],[\n          15,{\n            \"fee\": 2",
"000000\n          }\n        ],[\n         ",
" 16,{\n            \"fee\": 100000\n        ",
"  }\n        ],[\n          17,{\n         ",
"   \"fee\": 10000000\n          }\n        ]",
",[\n          18,{\n            \"fee\": 500",
"00000\n          }\n        ],[\n          ",
"19,{\n            \"fee\": 100000\n         ",
" }\n        ],[\n          20,{\n          ",
"  \"fee\": 500000000\n          }\n        ]",
",[\n          21,{\n            \"fee\": 200",
"0000\n          }\n        ],[\n          2",
"2,{\n            \"fee\": 2000000,\n        ",
"    \"price_per_kbyte\": 10\n          }\n  ",
"      ],[\n          23,{\n            \"fe",
"e\": 2000000,\n            \"price_per_kbyt",
"e\": 10\n          }\n        ],[\n         ",
" 24,{\n            \"fee\": 100000\n        ",
"  }\n        ],[\n          25,{\n         ",
"   \"fee\": 100000\n          }\n        ],[",
"\n          26,{\n            \"fee\": 10000",
"0\n          }\n        ],[\n          27,{",
"\n            \"fee\": 2000000,\n           ",
" \"price_per_kbyte\": 10\n          }\n     ",
"   ],[\n          28,{\n            \"fee\":",
" 0\n          }\n        ],[\n          29,",
"{\n            \"fee\": 500000000\n         ",
" }\n        ],[\n          30,{\n          ",
"  \"fee\": 2000000\n          }\n        ],[",
"\n          31,{\n            \"fee\": 10000",
"0\n          }\n        ],[\n          32,{",
"\n            \"fee\": 100000\n          }\n ",
"       ],[\n          33,{\n            \"f",
"ee\": 2000000\n          }\n        ],[\n   ",
"       34,{\n            \"fee\": 500000000",
"\n          }\n        ],[\n          35,{\n",
"            \"fee\": 100000,\n            \"",
"price_per_kbyte\": 10\n          }\n       ",
" ],[\n          36,{\n            \"fee\": 1",
"00000\n          }\n        ],[\n          ",
"37,{}\n        ],[\n          38,{\n       ",
"     \"fee\": 2000000,\n            \"price_",
"per_kbyte\": 10\n          }\n        ],[\n ",
"         39,{\n            \"fee\": 500000,",
"\n            \"price_per_output\": 500000\n",
"          }\n        ],[\n          40,{\n ",
"           \"fee\": 500000,\n            \"p",
"rice_per_output\": 500000\n          }\n   ",
"     ],[\n          41,{\n            \"fee",
"\": 500000\n          }\n        ],[\n      ",
"    42,{}\n        ],[\n          43,{\n   ",
"         \"fee\": 2000000\n          }\n    ",
"    ],[\n          44,{}\n        ],[\n    ",
"      45,{\n            \"fee\": 2000000\n  ",
"        }\n        ],[\n          46,{}\n  ",
"      ]\n      ],\n      \"scale\": 10000\n  ",
"  },\n    \"block_interval\": 5,\n    \"maint",
"enance_interval\": 86400,\n    \"maintenanc",
"e_skip_slots\": 3,\n    \"committee_proposa",
"l_review_period\": 1209600,\n    \"maximum_",
"transaction_size\": 2048,\n    \"maximum_bl",
"ock_size\": 2048000000,\n    \"maximum_time",
"_until_expiration\": 86400,\n    \"maximum_",
"proposal_lifetime\": 2419200,\n    \"maximu",
"m_asset_whitelist_authorities\": 10,\n    ",
"\"maximum_asset_feed_publishers\": 10,\n   ",
" \"maximum_witness_count\": 1001,\n    \"max",
"imum_committee_count\": 1001,\n    \"maximu",
"m_authority_membership\": 10,\n    \"reserv",
"e_percent_of_fee\": 2000,\n    \"network_pe",
"rcent_of_fee\": 2000,\n    \"lifetime_refer",
"rer_percent_of_fee\": 3000,\n    \"cashback",
"_vesting_period_seconds\": 31536000,\n    ",
"\"cashback_vesting_threshold\": 10000000,\n",
"    \"count_non_member_votes\": true,\n    ",
"\"allow_non_member_whitelists\": false,\n  ",
"  \"witness_pay_per_block\": 1000000,\n    ",
"\"worker_budget_per_day\": \"50000000000\",\n",
"    \"max_predicate_opcode\": 1,\n    \"fee_",
"liquidation_threshold\": 10000000,\n    \"a",
"ccounts_per_fee_scale\": 1000,\n    \"accou",
"nt_fee_scale_bitshifts\": 4,\n    \"max_aut",
"hority_depth\": 2,\n    \"extensions\": []\n ",
" },\n  \"initial_accounts\": [{\n      \"name",
"\": \"init0\",\n      \"owner_key\": \"BTS6MRyA",
"jQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5G",
"DW5CV\",\n      \"active_key\": \"BTS6MRyAjQq",
"8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5",
"CV\",\n      \"is_lifetime_member\": true\n  ",
"  },{\n      \"name\": \"init1\",\n      \"owne",
"r_key\": \"BTS6MRyAjQq8ud7hVNYcfnVPJqcVpsc",
"N5So8BhtHuGYqET5GDW5CV\",\n      \"active_k",
"ey\": \"BTS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5S",
"o8BhtHuGYqET5GDW5CV\",\n      \"is_lifetime",
"_member\": true\n    },{\n      \"name\": \"in",
"it2\",\n      \"owner_key\": \"BTS6MRyAjQq8ud",
"7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV\"",
",\n      \"active_key\": \"BTS6MRyAjQq8ud7hV",
"NYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV\",\n ",
"     \"is_lifetime_member\": true\n    },{\n",
"      \"name\": \"init3\",\n      \"owner_key\"",
": \"BTS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8B",
"htHuGYqET5GDW5CV\",\n      \"active_key\": \"",
"BTS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtH",
"uGYqET5GDW5CV\",\n      \"is_lifetime_membe",
"r\": true\n    },{\n      \"name\": \"init4\",\n",
"      \"owner_key\": \"BTS6MRyAjQq8ud7hVNYc",
"fnVPJqcVpscN5So8BhtHuGYqET5GDW5CV\",\n    ",
"  \"active_key\": \"BTS6MRyAjQq8ud7hVNYcfnV",
"PJqcVpscN5So8BhtHuGYqET5GDW5CV\",\n      \"",
"is_lifetime_member\": true\n    },{\n      ",
"\"name\": \"init5\",\n      \"owner_key\": \"BTS",
"6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGY",
"qET5GDW5CV\",\n      \"active_key\": \"BTS6MR",
"yAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET",
"5GDW5CV\",\n      \"is_lifetime_member\": tr",
"ue\n    },{\n      \"name\": \"init6\",\n      ",
"\"owner_key\": \"BTS6MRyAjQq8ud7hVNYcfnVPJq",
"cVpscN5So8BhtHuGYqET5GDW5CV\",\n      \"act",
"ive_key\": \"BTS6MRyAjQq8ud7hVNYcfnVPJqcVp",
"scN5So8BhtHuGYqET5GDW5CV\",\n      \"is_lif",
"etime_member\": true\n    },{\n      \"name\"",
": \"init7\",\n      \"owner_key\": \"BTS6MRyAj",
"Qq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GD",
"W5CV\",\n      \"active_key\": \"BTS6MRyAjQq8",
"ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5C",
"V\",\n      \"is_lifetime_member\": true\n   ",
" },{\n      \"name\": \"init8\",\n      \"owner",
"_key\": \"BTS6MRyAjQq8ud7hVNYcfnVPJqcVpscN",
"5So8BhtHuGYqET5GDW5CV\",\n      \"active_ke",
"y\": \"BTS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So",
"8BhtHuGYqET5GDW5CV\",\n      \"is_lifetime_",
"member\": true\n    },{\n      \"name\": \"ini",
"t9\",\n      \"owner_key\": \"BTS6MRyAjQq8ud7",
"hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV\",",
"\n      \"active_key\": \"BTS6MRyAjQq8ud7hVN",
"YcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV\",\n  ",
"    \"is_lifetime_member\": true\n    },{\n ",
"     \"name\": \"init10\",\n      \"owner_key\"",
": \"BTS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8B",
"htHuGYqET5GDW5CV\",\n      \"active_key\": \"",
"BTS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtH",
"uGYqET5GDW5CV\",\n      \"is_lifetime_membe",
"r\": true\n    },{\n      \"name\": \"nathan\",",
"\n      \"owner_key\": \"BTS6MRyAjQq8ud7hVNY",
"cfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV\",\n   ",
"   \"active_key\": \"BTS6MRyAjQq8ud7hVNYcfn",
"VPJqcVpscN5So8BhtHuGYqET5GDW5CV\",\n      ",
"\"is_lifetime_member\": false\n    }\n  ],\n ",
" \"initial_assets\": [],\n  \"initial_balanc",
"es\": [{\n      \"owner\": \"BTSFAbAx7yuxt725",
"qSZvfwWqkdCwp9ZnUama\",\n      \"asset_symb",
"ol\": \"BTS\",\n      \"amount\": \"10000000000",
"00000\"\n    }\n  ],\n  \"initial_vesting_bal",
"ances\": [],\n  \"initial_active_witnesses\"",
": 11,\n  \"initial_witness_candidates\": [{",
"\n      \"owner_name\": \"init0\",\n      \"blo",
"ck_signing_key\": \"BTS6MRyAjQq8ud7hVNYcfn",
"VPJqcVpscN5So8BhtHuGYqET5GDW5CV\"\n    },{",
"\n      \"owner_name\": \"init1\",\n      \"blo",
"ck_signing_key\": \"BTS6MRyAjQq8ud7hVNYcfn",
"VPJqcVpscN5So8BhtHuGYqET5GDW5CV\"\n    },{",
"\n      \"owner_name\": \"init2\",\n      \"blo",
"ck_signing_key\": \"BTS6MRyAjQq8ud7hVNYcfn",
"VPJqcVpscN5So8BhtHuGYqET5GDW5CV\"\n    },{",
"\n      \"owner_name\": \"init3\",\n      \"blo",
"ck_signing_key\": \"BTS6MRyAjQq8ud7hVNYcfn",
"VPJqcVpscN5So8BhtHuGYqET5GDW5CV\"\n    },{",
"\n      \"owner_name\": \"init4\",\n      \"blo",
"ck_signing_key\": \"BTS6MRyAjQq8ud7hVNYcfn",
"VPJqcVpscN5So8BhtHuGYqET5GDW5CV\"\n    },{",
"\n      \"owner_name\": \"init5\",\n      \"blo",
"ck_signing_key\": \"BTS6MRyAjQq8ud7hVNYcfn",
"VPJqcVpscN5So8BhtHuGYqET5GDW5CV\"\n    },{",
"\n      \"owner_name\": \"init6\",\n      \"blo",
"ck_signing_key\": \"BTS6MRyAjQq8ud7hVNYcfn",
"VPJqcVpscN5So8BhtHuGYqET5GDW5CV\"\n    },{",
"\n      \"owner_name\": \"init7\",\n      \"blo",
"ck_signing_key\": \"BTS6MRyAjQq8ud7hVNYcfn",
"VPJqcVpscN5So8BhtHuGYqET5GDW5CV\"\n    },{",
"\n      \"owner_name\": \"init8\",\n      \"blo",
"ck_signing_key\": \"BTS6MRyAjQq8ud7hVNYcfn",
"VPJqcVpscN5So8BhtHuGYqET5GDW5CV\"\n    },{",
"\n      \"owner_name\": \"init9\",\n      \"blo",
"ck_signing_key\": \"BTS6MRyAjQq8ud7hVNYcfn",
"VPJqcVpscN5So8BhtHuGYqET5GDW5CV\"\n    },{",
"\n      \"owner_name\": \"init10\",\n      \"bl",
"ock_signing_key\": \"BTS6MRyAjQq8ud7hVNYcf",
"nVPJqcVpscN5So8BhtHuGYqET5GDW5CV\"\n    }\n",
"  ],\n  \"initial_committee_candidates\": [",
"{\n      \"owner_name\": \"init0\"\n    },{\n  ",
"    \"owner_name\": \"init1\"\n    },{\n      ",
"\"owner_name\": \"init2\"\n    },{\n      \"own",
"er_name\": \"init3\"\n    },{\n      \"owner_n",
"ame\": \"init4\"\n    },{\n      \"owner_name\"",
": \"init5\"\n    },{\n      \"owner_name\": \"i",
"nit6\"\n    },{\n      \"owner_name\": \"init7",
"\"\n    },{\n      \"owner_name\": \"init8\"\n  ",
"  },{\n      \"owner_name\": \"init9\"\n    },",
"{\n      \"owner_name\": \"init10\"\n    }\n  ]",
",\n  \"initial_worker_candidates\": [],\n  \"",
"initial_chain_id\": \"aa34045518f1469a28fa",
"4578240d5f039afa9959c0b95ce3b39674efa691",
"fb21\",\n  \"immutable_parameters\": {\n    \"",
"min_committee_member_count\": 11,\n    \"mi",
"n_witness_count\": 11,\n    \"num_special_a",
"ccounts\": 0,\n    \"num_special_assets\": 0",
"\n  }\n}\n"
};

chain_id_type get_egenesis_chain_id()
{
   return chain_id_type( "30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f" );
}

void compute_egenesis_json( std::string& result )
{
   result.reserve( 9807 );
   result.resize(0);
   for( size_t i=0; i<246-1; i++ )
   {
      result.append( genesis_json_array[i], 40 );
   }
   result.append( std::string( genesis_json_array[ 246-1 ] ) );
   return;
}

fc::sha256 get_egenesis_json_hash()
{
   return fc::sha256( "30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f" );
}

} }
